version: "3.9"  

services:
  mid-autumn:
    image: phambaduong/movie-platform:latest
    container_name: mid-autumn
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
